name: 'Setup Node'
description: 'Install pnpm, Node.js and dependencies'
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile
